import { NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';
import { leadSchema } from '@/lib/validations';
import { sendEmail } from '@/lib/mailer';

export async function POST(request: Request) {
  try {
    const body = await request.json();

    const parsed = leadSchema.safeParse(body);
    if (!parsed.success) {
      return NextResponse.json(
        { error: 'Invalid input', issues: parsed.error.flatten() },
        { status: 400 },
      );
    }

    if (parsed.data.website && parsed.data.website.length > 0) {
      return NextResponse.json({ ok: true });
    }

    const { firstName, lastName, phone, email } = parsed.data;
    const name = `${firstName} ${lastName}`.trim();
    const userAgent = request.headers.get('user-agent') || undefined;
    const referer = request.headers.get('referer') || undefined;
    const origin = new URL(request.url).origin;

    const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
    const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;
    const db = createClient(supabaseUrl, supabaseKey);

    // Insert into leads — verification_token auto-generated by DB default
    let verificationToken: string | null = null;
    try {
      const { data, error } = await db
        .from('leads')
        .insert({
          name,
          first_name: firstName,
          last_name: lastName,
          phone,
          email,
          plan_key: 'plus',
          source: 'landing_page',
          user_agent: userAgent,
          referer,
        })
        .select('verification_token')
        .single();

      if (!error && data) verificationToken = data.verification_token;
    } catch (err) {
      console.error('[member] DB insert failed:', err);
    }

    const notifyEmail = process.env.NOTIFY_EMAIL || 'ishlokchavan@gmail.com';
    const verifyUrl = verificationToken
      ? `${origin}/api/verify?token=${verificationToken}&type=member`
      : null;

    // Verification email to member
    try {
      await sendEmail({
        to: email,
        subject: "You're in — confirm your iClose email",
        html: `
          <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:520px;margin:0 auto;color:#1d1d1f;">
            <p style="font-size:24px;font-weight:600;margin-bottom:8px;letter-spacing:-0.02em;">Welcome, ${firstName}.</p>
            <p style="font-size:17px;color:#6e6e73;line-height:1.55;margin-bottom:20px;letter-spacing:-0.01em;">
              You've joined the iClose founding cohort as a <strong style="color:#1d1d1f;">Member</strong>. One last step — confirm your email to secure your place.
            </p>
            ${verifyUrl ? `
            <a href="${verifyUrl}" style="display:inline-block;margin-bottom:24px;padding:14px 28px;background:#1d1d1f;color:#ffffff;border-radius:100px;font-size:15px;font-weight:500;text-decoration:none;letter-spacing:-0.01em;">
              Confirm my email
            </a>
            <p style="font-size:13px;color:#a1a1a6;margin-bottom:20px;">Or copy this link: <a href="${verifyUrl}" style="color:#0071e3;">${verifyUrl}</a></p>
            ` : ''}
            <p style="font-size:17px;color:#6e6e73;line-height:1.55;margin-bottom:28px;letter-spacing:-0.01em;">
              Founding members get first access and locked-in terms before public launch.
            </p>
            <p style="font-size:15px;color:#6e6e73;">— The iClose team</p>
            <hr style="border:none;border-top:1px solid #d2d2d7;margin:32px 0;"/>
            <p style="font-size:12px;color:#a1a1a6;">iClose · Dubai, UAE · <a href="https://iclose.ae" style="color:#0071e3;text-decoration:none;">iclose.ae</a></p>
          </div>
        `,
      });
    } catch (err) {
      console.error('[member] verification email failed:', err);
    }

    // Admin notification
    try {
      await sendEmail({
        to: notifyEmail,
        subject: `New Member signup: ${name}`,
        html: `
          <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:520px;color:#1d1d1f;">
            <p style="font-size:18px;font-weight:600;margin-bottom:16px;">New Member signup</p>
            <table style="width:100%;border-collapse:collapse;font-size:15px;">
              <tr><td style="padding:8px 0;color:#6e6e73;width:80px;">Name</td><td style="padding:8px 0;">${name}</td></tr>
              <tr><td style="padding:8px 0;color:#6e6e73;">Email</td><td style="padding:8px 0;">${email}</td></tr>
              <tr><td style="padding:8px 0;color:#6e6e73;">Phone</td><td style="padding:8px 0;">${phone}</td></tr>
              <tr><td style="padding:8px 0;color:#6e6e73;">Plan</td><td style="padding:8px 0;">Plus (default)</td></tr>
              <tr><td style="padding:8px 0;color:#6e6e73;">Source</td><td style="padding:8px 0;">${referer || 'direct'}</td></tr>
              <tr><td style="padding:8px 0;color:#6e6e73;">Verified</td><td style="padding:8px 0;">Pending</td></tr>
            </table>
          </div>
        `,
      });
    } catch (err) {
      console.error('[member] admin notification failed:', err);
    }

    return NextResponse.json({ ok: true });
  } catch (err) {
    console.error('Lead API error:', err);
    return NextResponse.json(
      { error: 'Server error. Please try again.' },
      { status: 500 },
    );
  }
}
